name: Some tests

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      IMAGE: ghcr.io/ludovicm67/test

    steps:
      - name: Docker meta
        uses: zazuko/action-docker-meta@main
        id: docker_meta
        with:
          images: $IMAGE

      - run: echo "${IMAGE}:${{ github.run_id	}},${{ steps.docker_meta.outputs.tags }}"
